# Change these first
owner: Pawebf1 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Google Cloud
    url: https://cloud.google.com/?hl=pl
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: AWS
    url: https://aws.amazon.com/
  - name: Github
    url: https://github.com/
  - name: Gitlab
    url: https://about.gitlab.com/
  # - name: Test Broken Site
  #   url: https://thissitedoesnotexist.koj.co

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: Uptime monitor and status page
  introMessage: This is a status page which uses **real-time** data from our repository
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
